#!/bin/sh
# Initial script for Linux Live Kit
# Author: Tomas M <http://www.linux-live.org/>

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

. /lib/config
. /lib/livekitlib

transfer_initramfs

MEMORY=/memory
CHANGES=$MEMORY/changes
UNION=$MEMORY/union
DATAMNT=$MEMORY/data
BUNDLES=$MEMORY/bundles

header "Live Kit init <http://www.linux-live.org/>"

init_proc_sysfs

debug_start
                                                                                                                                                       debug_shell
# load some modules manually first, then modprobe everything we have
init_devs
init_aufs
init_zram

# modprobe all devices excluding network drivers
modprobe_everything -v /drivers/net/

# find data dir with filesystem bundles
DATA="$(find_data 45 "$DATAMNT")"
check_data_found "$DATA"
                                                                                                                                                      debug_shell
# setup persistent changes, if possible
persistent_changes "$DATA" "$CHANGES"
                                                                                                                                                      debug_shell
# copy to RAM if needed
DATA="$(copy_to_ram "$DATA" "$CHANGES")"

# mount bundles
mount_bundles "$DATA" "$BUNDLES"
                                                                                                                                                      debug_shell
# init aufs union, or setup overlayfs union
init_union "$CHANGES" "$UNION" "$BUNDLES"

# Remount overlayfs as rw
mount $UNION -o remount,rw

# add data to aufs union
union_append_bundles "$BUNDLES" "$UNION"
                                                                                                                                                      debug_shell
# rootcopy
copy_rootcopy_content "$DATA" "$UNION"

# create fstab
fstab_create "$UNION" "$DATAMNT"
                                                                                                                                                      debug_shell
# run user custom preinit
user_preinit "$DATA" "$UNION"

# MLFS: fix s6base
s6-rmrf -rf $UNION/etc/s6/base
s6-linux-init-maker -1  -t 2 -L -D default -f $UNION/etc/s6-linux-init/skel -p "/usr/bin:/usr/sbin:/bin:/sbin" \
	-G "/sbin/agetty -L -8 tty1 115200" -c /etc/s6/base -u root -U utmp $UNION/etc/s6/base

header "Live Kit done, starting $LIVEKITNAME"
change_root "$UNION"

# MLFS: new rootfs(/) should be rw
mount -v / -o rw,remount

header "!!ERROR occured, you shouldn't be here.!!"
/bin/sh
